In [72]:
import os

print(os.getcwd())

C:\Users\Preethi\Desktop\AHT_Root_Cause_Project

In [73]:
import os

print(os.listdir("data"))

['AHT_Root_Cause_Synthetic_Data_v3.xlsx']

In [74]:
import pandas as pd

df = pd.read_excel("data/AHT_Root_Cause_Synthetic_Data_v3.xlsx")

df.head()

,Chat_ID,Date,Agent_ID,Shift,Chat_Category,Resolution_Type,FRT_sec,Agent_Response_sec,Customer_Response_sec,Navigation_Time_sec,Technical_Error,Transferred_to_Supervisor_or_Escalated,Repeat_Messages,Total_Messages,Applications_Used,Resolution_Status,Customer_Sentiment,CSAT,AHT_sec
0,CH00001,2025-03-29,AG162,Mid Shift (10 AM EST),Promise to Pay,Promise to Pay,21,45,66,34,Yes,No,2,20,3,Unresolved,Negative,2,1104
1,CH00002,2025-04-18,AG144,Mid Shift (10 AM EST),Payment,Payment Completed,28,37,68,30,No,No,2,19,4,Resolved,Neutral,3,1003
2,CH00003,2025-03-21,AG129,Mid Shift (10 AM EST),Promise to Pay,Promise to Pay,9,36,61,27,No,No,1,19,3,Resolved,Neutral,3,885
3,CH00004,2025-05-30,AG149,Mid Shift (10 AM EST),Payment Dispute,Dispute Filed,19,41,73,38,No,Yes,2,18,5,Escalated,Negative,2,1204
4,CH00005,2025-04-21,AG102,Mid Shift (10 AM EST),Fraud,Fraud Investigation,25,47,68,35,Yes,No,4,30,5,Unresolved,Negative,2,1233

In [75]:
df.shape

(10000, 19)

In [76]:
df.columns

Index(['Chat_ID', 'Date', 'Agent_ID', 'Shift', 'Chat_Category',
       'Resolution_Type', 'FRT_sec', 'Agent_Response_sec',
       'Customer_Response_sec', 'Navigation_Time_sec', 'Technical_Error',
       'Transferred_to_Supervisor_or_Escalated', 'Repeat_Messages',
       'Total_Messages', 'Applications_Used', 'Resolution_Status',
       'Customer_Sentiment', 'CSAT', 'AHT_sec'],
      dtype='str')

In [77]:
print(df['Customer_Sentiment'])

0       Negative
1        Neutral
2        Neutral
3       Negative
4       Negative
          ...
9995     Neutral
9996    Negative
9997     Neutral
9998     Neutral
9999    Negative
Name: Customer_Sentiment, Length: 10000, dtype: str

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Chat_ID                                 10000 non-null  str
 1   Date                                    10000 non-null  str
 2   Agent_ID                                10000 non-null  str
 3   Shift                                   10000 non-null  str
 4   Chat_Category                           10000 non-null  str
 5   Resolution_Type                         10000 non-null  str
 6   FRT_sec                                 10000 non-null  int64
 7   Agent_Response_sec                      10000 non-null  int64
 8   Customer_Response_sec                   10000 non-null  int64
 9   Navigation_Time_sec                     10000 non-null  int64
 10  Technical_Error                         10000 non-null  str
 11  Transferred_to_Supervisor_or_Escalated  10000 non-null  str
 12  Repeat_Messages                         10000 non-null  int64
 13  Total_Messages                          10000 non-null  int64
 14  Applications_Used                       10000 non-null  int64
 15  Resolution_Status                       10000 non-null  str
 16  Customer_Sentiment                      10000 non-null  str
 17  CSAT                                    10000 non-null  int64
 18  AHT_sec                                 10000 non-null  int64
dtypes: int64(9), str(10)
memory usage: 1.4 MB

In [79]:
df.describe()

,FRT_sec,Agent_Response_sec,Customer_Response_sec,Navigation_Time_sec,Repeat_Messages,Total_Messages,Applications_Used,CSAT,AHT_sec
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,17.980200,41.81200,61.872100,31.811000,2.404000,21.211400,3.899300,2.610500,1027.456000
std,6.103305,5.22647,7.839585,4.415793,0.950302,3.814127,0.695275,0.526324,100.228043
min,8.000000,30.00000,44.000000,22.000000,1.000000,13.000000,3.000000,2.000000,777.000000
25%,13.000000,38.00000,56.000000,29.000000,2.000000,19.000000,3.000000,2.000000,947.000000
50%,18.000000,42.00000,62.000000,32.000000,2.000000,21.000000,4.000000,3.000000,1017.000000
75%,23.000000,45.00000,67.000000,35.000000,3.000000,24.000000,4.000000,3.000000,1099.000000
max,28.000000,54.00000,80.000000,42.000000,4.000000,30.000000,5.000000,5.000000,1404.000000

In [80]:
df.isnull().sum()

Chat_ID                                   0
Date                                      0
Agent_ID                                  0
Shift                                     0
Chat_Category                             0
Resolution_Type                           0
FRT_sec                                   0
Agent_Response_sec                        0
Customer_Response_sec                     0
Navigation_Time_sec                       0
Technical_Error                           0
Transferred_to_Supervisor_or_Escalated    0
Repeat_Messages                           0
Total_Messages                            0
Applications_Used                         0
Resolution_Status                         0
Customer_Sentiment                        0
CSAT                                      0
AHT_sec                                   0
dtype: int64

In [81]:
df["Date"]=pd.to_datetime(df["Date"])

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Chat_ID                                 10000 non-null  str
 1   Date                                    10000 non-null  datetime64[us]
 2   Agent_ID                                10000 non-null  str
 3   Shift                                   10000 non-null  str
 4   Chat_Category                           10000 non-null  str
 5   Resolution_Type                         10000 non-null  str
 6   FRT_sec                                 10000 non-null  int64
 7   Agent_Response_sec                      10000 non-null  int64
 8   Customer_Response_sec                   10000 non-null  int64
 9   Navigation_Time_sec                     10000 non-null  int64
 10  Technical_Error                         10000 non-null  str
 11  Transferred_to_Supervisor_or_Escalated  10000 non-null  str
 12  Repeat_Messages                         10000 non-null  int64
 13  Total_Messages                          10000 non-null  int64
 14  Applications_Used                       10000 non-null  int64
 15  Resolution_Status                       10000 non-null  str
 16  Customer_Sentiment                      10000 non-null  str
 17  CSAT                                    10000 non-null  int64
 18  AHT_sec                                 10000 non-null  int64
dtypes: datetime64[us](1), int64(9), str(9)
memory usage: 1.4 MB

In [83]:
# Module 2 - Exploratory Data Analysis (EDA)

In [84]:
#2.1 Understanding columns

In [85]:
df["Chat_Category"]

0         Promise to Pay
1                Payment
2         Promise to Pay
3        Payment Dispute
4                  Fraud
              ...
9995    Checking Account
9996               Fraud
9997              Wallet
9998              Wallet
9999            Hardship
Name: Chat_Category, Length: 10000, dtype: str

In [86]:
df["Chat_Category"].head()

0     Promise to Pay
1            Payment
2     Promise to Pay
3    Payment Dispute
4              Fraud
Name: Chat_Category, dtype: str

In [87]:
df["Chat_Category"].unique()

<StringArray>
[     'Promise to Pay',             'Payment',     'Payment Dispute',
               'Fraud',            'Hardship', 'Transaction Dispute',
    'Checking Account',          'Debit Card',        'Disconnected',
              'Wallet']
Length: 10, dtype: str

In [88]:
df["Chat_Category"].nunique()

10

In [89]:
df["Chat_Category"].value_counts()

Chat_Category
Fraud                  1022
Checking Account       1021
Payment Dispute        1015
Disconnected           1012
Promise to Pay         1004
Payment                1003
Wallet                  999
Transaction Dispute     996
Hardship                975
Debit Card              953
Name: count, dtype: int64

In [90]:
df["Shift"].unique()

<StringArray>
[    'Mid Shift (10 AM EST)', 'Closing Shift (12 PM EST)',
  'Opening Shift (8 AM EST)']
Length: 3, dtype: str

In [91]:
df["Shift"].value_counts()

Shift
Opening Shift (8 AM EST)     3395
Closing Shift (12 PM EST)    3304
Mid Shift (10 AM EST)        3301
Name: count, dtype: int64

In [92]:
df["Shift"].value_counts().sum()

np.int64(10000)

In [93]:
df["Resolution_Type"].value_counts()

Resolution_Type
RPC                    3985
Dispute Filed          2011
Fraud Investigation    1022
Promise to Pay         1004
Payment Completed      1003
Payment Plan            975
Name: count, dtype: int64

In [94]:
df["Resolution_Type"].unique()

<StringArray>
[     'Promise to Pay',   'Payment Completed',       'Dispute Filed',
 'Fraud Investigation',        'Payment Plan',                 'RPC']
Length: 6, dtype: str

In [95]:
df["Technical_Error"].value_counts()

Technical_Error
No     8739
Yes    1261
Name: count, dtype: int64

In [96]:
df["Transferred_to_Supervisor_or_Escalated"].value_counts()

Transferred_to_Supervisor_or_Escalated
No     9015
Yes     985
Name: count, dtype: int64

In [97]:
df["Resolution_Status"].value_counts()

Resolution_Status
Resolved      5955
Unresolved    3212
Escalated      833
Name: count, dtype: int64

In [98]:
df["Customer_Sentiment"].value_counts()

Customer_Sentiment
Neutral     5851
Negative    4045
Positive     104
Name: count, dtype: int64

In [99]:
# 2.2 Business Exploration

In [100]:
#1. Overall AHT

In [101]:
df["AHT_sec"].mean()

np.float64(1027.456)

In [102]:
#2. Avg of AHT by shift

In [103]:
df.groupby("Shift")["AHT_sec"].mean().sort_values(ascending=False)

Shift
Mid Shift (10 AM EST)        1029.202666
Opening Shift (8 AM EST)     1027.315758
Closing Shift (12 PM EST)    1025.855024
Name: AHT_sec, dtype: float64

In [104]:
#3.AHT by Chat category

In [105]:
df.groupby("Chat_Category")["AHT_sec"].mean().sort_values(ascending=False)

Chat_Category
Fraud                  1148.048924
Transaction Dispute    1124.646586
Payment Dispute        1109.304433
Hardship               1094.463590
Promise to Pay          988.705179
Payment                 980.872383
Debit Card              979.019937
Checking Account        970.162586
Wallet                  957.815816
Disconnected            920.143281
Name: AHT_sec, dtype: float64

In [106]:
#4. AHT by Resolution type

In [107]:
df.groupby("Resolution_Type")["AHT_sec"].mean().sort_values(ascending=False)

Resolution_Type
Fraud Investigation    1148.048924
Dispute Filed          1116.903033
Payment Plan           1094.463590
Promise to Pay          988.705179
Payment Completed       980.872383
RPC                     956.483061
Name: AHT_sec, dtype: float64

In [108]:
#5. AHT by FRT

In [109]:
df.groupby("FRT_sec")["AHT_sec"].mean().sort_values(ascending=False)

FRT_sec
27    1042.990234
28    1038.026157
24    1035.675737
13    1032.366594
25    1032.214442
20    1032.052192
15    1030.655629
22    1030.380550
26    1029.623126
23    1029.042373
21    1028.175476
19    1027.611910
10    1027.105809
17    1026.073222
9     1023.978261
11    1021.562637
14    1021.322581
12    1021.118896
18    1018.993814
8     1014.639442
16    1012.785872
Name: AHT_sec, dtype: float64

In [110]:
#6. AHT by Agent Response time

In [111]:
df.groupby("Agent_Response_sec")["AHT_sec"].mean().sort_values(ascending=False)

Agent_Response_sec
54    1187.564103
53    1161.935897
52    1144.676829
51    1138.060241
49    1131.059172
50    1130.328814
48    1124.668810
47    1098.207447
46    1069.116635
43    1044.604027
45    1044.026912
44    1042.559816
42    1023.971114
40    1014.188321
41    1012.721408
39     996.666096
38     977.796512
37     966.232990
36     954.473568
35     949.458947
34     948.416867
33     933.877193
32     911.400000
31     902.894737
30     899.076923
Name: AHT_sec, dtype: float64

In [112]:
#7. AHT by Customer_Response_sec

In [113]:
df.groupby("Customer_Response_sec")["AHT_sec"].mean().sort_values(ascending=False)

Customer_Response_sec
80    1192.929825
79    1185.245902
77    1169.515152
78    1169.471154
76    1149.468927
75    1143.154696
74    1140.776190
73    1137.870466
72    1134.250000
70    1129.037037
71    1125.854545
69    1111.457364
68    1082.641873
67    1067.298165
65    1048.760369
64    1046.143162
66    1041.845511
63    1039.110132
62    1026.316794
61    1011.106557
60    1010.807963
59    1003.395034
58     992.883610
57     978.341346
56     963.309816
54     955.605960
55     954.629969
53     951.507246
52     942.888136
51     934.541538
50     929.903571
49     913.605263
48     911.645833
46     901.645833
45     890.759259
47     888.745098
44     876.065217
Name: AHT_sec, dtype: float64

In [114]:
#8. AHT by Navigation_Time_sec

In [115]:
df.groupby("Navigation_Time_sec")["AHT_sec"].mean().sort_values(ascending=False)

Navigation_Time_sec
41    1171.346939
42    1167.436782
40    1147.289963
39    1137.597403
38    1137.181333
37    1126.222222
36    1099.026030
35    1063.614958
33    1050.565385
34    1048.665459
32    1026.802661
31    1011.125882
30    1004.046272
29     979.196899
28     953.058824
27     952.604317
26     950.640152
25     941.310345
24     914.458564
23     900.215190
22     895.240000
Name: AHT_sec, dtype: float64

In [116]:
#9. AHT by Technical_Error

In [117]:
df.groupby("Technical_Error")["AHT_sec"].mean().sort_values(ascending=False)

Technical_Error
Yes    1121.125297
No     1013.939924
Name: AHT_sec, dtype: float64

In [118]:
#10. AHT by Transferred_to_Supervisor_or_Escalated

In [119]:
df.groupby("Transferred_to_Supervisor_or_Escalated")["AHT_sec"].mean().sort_values(ascending=False)

Transferred_to_Supervisor_or_Escalated
Yes    1150.216244
No     1014.042928
Name: AHT_sec, dtype: float64

In [120]:
#11. AHT by Repeat_Messages

In [121]:
df.groupby("Repeat_Messages")["AHT_sec"].mean().sort_values(ascending=False)

Repeat_Messages
4    1155.370651
3    1048.338257
2    1013.438862
1     930.182504
Name: AHT_sec, dtype: float64

In [122]:
#12. AHT by Total_Messages

In [123]:
df.groupby("Total_Messages")["AHT_sec"].mean().sort_values(ascending=False)

Total_Messages
30    1158.625899
28    1158.340136
29    1144.425373
26    1079.206250
25    1075.449416
27    1073.384755
22    1054.790828
24    1054.456180
23    1052.960042
19    1009.655622
20    1007.883744
21    1007.610572
18     983.789675
16     977.197749
17     977.158451
14     936.188119
15     930.572614
13     929.203883
Name: AHT_sec, dtype: float64

In [124]:
#13.AHT by Applications_Used

In [125]:
df.groupby("Applications_Used")["AHT_sec"].mean().sort_values(ascending=False)

Applications_Used
5    1129.445010
4    1028.789339
3     957.762370
Name: AHT_sec, dtype: float64

In [126]:
#14.AHT by Resolution_Status

In [127]:
df.groupby("Resolution_Status")["AHT_sec"].mean().sort_values(ascending=False)

Resolution_Status
Escalated     1173.885954
Unresolved    1117.087173
Resolved       958.627876
Name: AHT_sec, dtype: float64

In [128]:
#15.AHT by Customer_Sentiment

In [129]:
df.groupby("Customer_Sentiment")["AHT_sec"].mean().sort_values(ascending=False)

Customer_Sentiment
Negative    1128.783931
Neutral      960.852846
Positive     833.451923
Name: AHT_sec, dtype: float64

In [130]:
#16.AHT by CSAT

In [131]:
df.groupby("CSAT")["AHT_sec"].mean().sort_values(ascending=False)

CSAT
2    1128.783931
3     960.852846
5     834.130435
4     832.913793
Name: AHT_sec, dtype: float64

In [132]:
#Module-3 Root cause analysis

In [ ]:
#3.1 Understanding operational complexity by chat category

In [ ]:
#Comparing no.of chat transfers to supervisor by chat category ?

In [134]:
df.groupby("Chat_Category")["Transferred_to_Supervisor_or_Escalated"].value_counts()

Chat_Category        Transferred_to_Supervisor_or_Escalated
Checking Account     No                                        924
                     Yes                                        97
Debit Card           No                                        865
                     Yes                                        88
Disconnected         No                                        954
                     Yes                                        58
Fraud                No                                        888
                     Yes                                       134
Hardship             No                                        869
                     Yes                                       106
Payment              No                                        909
                     Yes                                        94
Payment Dispute      No                                        893
                     Yes                                       122
Promise to Pay       No                                        924
                     Yes                                        80
Transaction Dispute  No                                        867
                     Yes                                       129
Wallet               No                                        922
                     Yes                                        77
Name: count, dtype: int64

In [ ]:
#Comparing average repeated messages by chat category ?

In [135]:
df.groupby("Chat_Category")["Repeat_Messages"].mean().sort_values(ascending=False)

Chat_Category
Transaction Dispute    3.026104
Payment Dispute        3.000985
Fraud                  2.998043
Hardship               2.973333
Checking Account       2.043095
Payment                2.038883
Debit Card             2.008395
Promise to Pay         2.000996
Disconnected           1.991107
Wallet                 1.949950
Name: Repeat_Messages, dtype: float64

In [ ]:
#Comparing average Aplications used by chat category ?

In [136]:
df.groupby("Chat_Category")["Applications_Used"].mean().sort_values(ascending=False)

Chat_Category
Hardship               4.495385
Fraud                  4.491194
Transaction Dispute    4.486948
Payment Dispute        4.486700
Wallet                 3.530531
Disconnected           3.519763
Payment                3.507478
Promise to Pay         3.501992
Debit Card             3.491081
Checking Account       3.474045
Name: Applications_Used, dtype: float64

In [ ]:
#Comparing average Navigation time by chat category ?

In [137]:
df.groupby("Chat_Category")["Navigation_Time_sec"].mean().sort_values(ascending=False)

Chat_Category
Fraud                  36.901174
Payment Dispute        35.141872
Transaction Dispute    34.961847
Hardship               34.217436
Promise to Pay         30.963147
Payment                30.124626
Debit Card             29.923400
Checking Account       29.848188
Wallet                 28.974975
Disconnected           26.980237
Name: Navigation_Time_sec, dtype: float64

In [ ]:
#Comparing average customer response time by chat category ?

In [138]:
df.groupby("Chat_Category")["Customer_Response_sec"].mean().sort_values(ascending=False)

Chat_Category
Fraud                  70.928571
Transaction Dispute    69.196787
Payment Dispute        67.167488
Hardship               65.615385
Promise to Pay         59.943227
Debit Card             58.965373
Payment                58.835494
Checking Account       57.918707
Wallet                 56.953954
Disconnected           53.103755
Name: Customer_Response_sec, dtype: float64

In [ ]:
#Comparing average agent response time by chat category ?

In [139]:
df.groupby("Chat_Category")["Agent_Response_sec"].mean().sort_values(ascending=False)

Chat_Category
Fraud                  48.059687
Transaction Dispute    46.131526
Payment Dispute        44.895567
Hardship               44.028718
Promise to Pay         41.033865
Debit Card             40.279119
Payment                39.892323
Wallet                 38.875876
Checking Account       38.875612
Disconnected           36.001976
Name: Agent_Response_sec, dtype: float64

In [ ]:
#3.2 Validating drivers of AHT

In [ ]:
#Comparing average AHT by Repeated Messages

In [140]:
df.groupby("Repeat_Messages")["AHT_sec"].mean().sort_values()

Repeat_Messages
1     930.182504
2    1013.438862
3    1048.338257
4    1155.370651
Name: AHT_sec, dtype: float64

In [ ]:
#Comparing average AHT by Navigation time

In [142]:
df["Navigation_Group"]=pd.cut(df["Navigation_Time_sec"], 
bins=[0, 25, 30, 35, 40, 100], labels=["0-25", "26-30","31-35","36-40", "40+"])

In [143]:
df.groupby("Navigation_Group")["AHT_sec"].mean().sort_values()

Navigation_Group
0-25      925.881068
26-30     970.985007
31-35    1039.024743
36-40    1127.101575
40+      1169.508108
Name: AHT_sec, dtype: float64

In [ ]:
#Comparing average AHT by Customer Response Time

In [160]:
df["Customer_Responsetime_Group"]=pd.cut(df["Customer_Response_sec"], 
bins=[40, 50, 60, 70, 80, 90], labels=["40-50", "51-60","61-70","71-80", "81+"])

In [161]:
df.groupby("Customer_Responsetime_Group")["AHT_sec"].mean().sort_values()

Customer_Responsetime_Group
40-50     913.017882
51-60     972.169010
61-70    1052.363107
71-80    1146.135649
Name: AHT_sec, dtype: float64

In [ ]:
#Comparing AHT by Agent Response Time

In [166]:
df["Agent_Responsetime_Group"]=pd.cut(df["Agent_Response_sec"], 
bins=[20, 30, 40, 50, 60,70], labels=["20-30", "31-40","41-50","51-60", "61+"])

In [167]:
df.groupby("Agent_Responsetime_Group")["AHT_sec"].mean().sort_values()

Agent_Responsetime_Group
20-30     899.076923
31-40     971.063282
41-50    1058.404482
51-60    1150.026362
Name: AHT_sec, dtype: float64

In [ ]:
#Technical Error VS AHT

In [168]:
df.groupby("Technical_Error")["AHT_sec"].mean()

Technical_Error
No     1013.939924
Yes    1121.125297
Name: AHT_sec, dtype: float64

In [ ]:
#Escalations VS AHT?

In [169]:
df.groupby("Transferred_to_Supervisor_or_Escalated")["AHT_sec"].mean()

Transferred_to_Supervisor_or_Escalated
No     1014.042928
Yes    1150.216244
Name: AHT_sec, dtype: float64

In [170]:
df.to_excel(
    "data/AHT_Root_Cause_Final.xlsx",
    index=False
)

In [172]:
import os

print(os.listdir("data"))

['AHT_Root_Cause_Final.xlsx', 'AHT_Root_Cause_Synthetic_Data_v3.xlsx']

In [173]:
df.groupby("Chat_Category")["AHT_sec"].mean()

Chat_Category
Checking Account        970.162586
Debit Card              979.019937
Disconnected            920.143281
Fraud                  1148.048924
Hardship               1094.463590
Payment                 980.872383
Payment Dispute        1109.304433
Promise to Pay          988.705179
Transaction Dispute    1124.646586
Wallet                  957.815816
Name: AHT_sec, dtype: float64

In [174]:
df["CSAT"].mean()

np.float64(2.6105)